<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.teb.practice</groupId>
        <artifactId>test-programs</artifactId>
        <version>1.4.1</version>
    </parent>

    <artifactId>test-pit-mutation-programs</artifactId>

    <profiles>
        <profile>
            <id>mutate</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-maven</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>mutationCoverage</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <mutationThreshold>100</mutationThreshold>
                            <coverageThreshold>100</coverageThreshold>
                            <targetClasses>com.teb.practice.*</targetClasses>
                            <targetTests>com.teb.practice.*</targetTests>
                        </configuration>
                        <dependencies>
                            <!-- Required dependency for pitest on JUnit5 -->
                            <dependency>
                                <groupId>org.pitest</groupId>
                                <artifactId>pitest-junit5-plugin</artifactId>
                                <version>1.2.3</version>
                            </dependency>
                        </dependencies>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>