name: Test Programs CI

# Run workflow on push or pull request to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java (JDK 17)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 23
          distribution: 'temurin'

      # Build project with Maven
      - name: Build with Maven
        run: mvn clean install

      # Run tests
      - name: Run tests
        run: mvn test